name: mesh_funcspace
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.2
  - imageio=2.4.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - pandas=0.23.4
  - pillow=5.3.0
  - pyembree=0.1.4
  - pytest=4.0.2
  - python=3.6.7
  - pytorch=1.0.0
  - pyyaml=3.13
  - scikit-image=0.14.1
  - scipy=1.1.0
  - tensorboardx=1.4
  - torchvision=0.2.1
  - tqdm=4.28.1
  - trimesh=2.37.7
  - pip:
    - h5py==2.9.0
    - plyfile==0.7

